import Head from 'next/head';
import { subtitleFont, titleFont } from '../utils/fonts';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed top-0 left-0 right-0 bottom-0 -z-50  bg-img-home-mobile bg-cover bg-no-repeat sm:bg-img-home-tablet lg:bg-img-home-desktop " />
      <div className="mx-10 mt-20 mb-12 text-center text-white sm:mx-24 sm:mt-40 lg:mx-40 lg:flex lg:text-left">
        <div className=" lg:basis-2/4 lg:pr-32">
          <h2
            className={`${subtitleFont.className} uppercase tracking-[2.7px] text-[#D0D6F9] sm:text-xl`}
          >
            So, you want travel to space
          </h2>
          <h1
            className={`${titleFont.className}  my-6 text-7xl uppercase sm:text-9xl`}
          >
            Space
          </h1>
          <p className="text-lg  text-[#D0D6F9]  ">
            Let’s face it; if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </p>
        </div>

        <div className="mt-20 lg:basis-2/4  lg:text-center">
          <Link href={'/destination'}>
            <button
              className={`${titleFont.className} 
               relative h-40 w-40 rounded-full bg-white text-center text-2xl uppercase text-[#0B0D17] before:absolute before:top-0 before:left-0 before:h-full before:w-full before:rounded-full before:bg-white/10 before:transition-transform hover:before:scale-150 lg:h-52 lg:w-52`}
            >
              Explore
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}
