import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/image';
import { subtitleFont, titleFont } from '../../utils/fonts';
import { spaceLaunchData } from '../../utils/constants';

export default function Home() {
  const [spaceId, setSpaceId] = useState(0);
  const [active, setActive] = useState(0);

  const { title, subtitle, text, image } = spaceLaunchData[spaceId];

  const handleClick = (id) => {
    setSpaceId(id);
    setActive(id);
  };

  return (
    <div>
      <Head>
        <title>Space Tourism - Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed top-0 left-0 right-0 bottom-0 -z-10  bg-img-tech-mobile bg-cover bg-no-repeat sm:bg-img-tech-tablet lg:bg-img-tech-desktop" />

      <div
        className="flex flex-col items-center gap-7
         py-8 text-white lg:items-start lg:pl-36"
      >
        <h2
          className={`${subtitleFont.className} mt-4 px-8 uppercase tracking-[2.7px] sm:self-start sm:text-xl lg:px-0 lg:text-2xl`}
        >
          <span className="mr-3 font-bold opacity-25">03</span>
          Space Launch 101
        </h2>

        <div className=" flex flex-col items-center gap-7 lg:mt-8 lg:flex-row  lg:justify-start ">
          <div className="relative h-52 w-full sm:h-80 lg:order-2 lg:h-[527px] lg:w-[515px] ">
            <Image
              src={image[0]}
              alt="space"
              className="object-cover lg:hidden "
              sizes="100vw"
              fill
            />
            <Image
              src={image[1]}
              alt="space"
              className=" hidden object-cover lg:block"
              sizes="100vw"
              fill
            />
          </div>
          <div className="flex gap-4 lg:flex-col ">
            {spaceLaunchData.map((item) => (
              <a
                key={item.id}
                className={`flex h-10 w-10 cursor-pointer items-center justify-center rounded-full border border-white/25 sm:h-12 sm:w-12 lg:ml-0 lg:mr-5 lg:h-16 lg:w-16 lg:text-xl ${
                  active === item.id && 'bg-white text-[#0B0D17]'
                }`}
                onClick={() => handleClick(item.id)}
                a
              >
                {item.id + 1}
              </a>
            ))}
          </div>
          <div className="flex flex-col items-center gap-2 sm:gap-5 lg:order-1 lg:flex-1 lg:items-start lg:pr-4">
            <h2
              className={`${subtitleFont.className}  uppercase tracking-[2.36px] text-[#D0D6F9]`}
            >
              {subtitle}
            </h2>
            <h1
              className={`${titleFont.className} mb-1 text-2xl uppercase sm:text-4xl lg:text-5xl`}
            >
              {title}
            </h1>
            <p className="px-10 text-center text-[#D0D6F9] sm:px-40 sm:leading-7 lg:px-0 lg:text-left lg:text-lg ">
              {text}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
